export class FriendlyNames{
    constructor(){
        this.names = {
            "Primitive":"Simple",
            "BoxGeometry":"Box",
            "CircleGeometry":"Circle",
            "ConeGeometry":"Cone",
            "CylinderGeometry":"Cylinder",
            "DodecahedronGeometry":"Dodecahedron",
            "IcosahedronGeometry":"Icosahedron",
            "OctahedronGeometry":"Octahedron",
            "PlaneGeometry":"Plane",
            "RingGeometry":"Ring",
            "SphereGeometry":"Sphere",
            "TetrahedronGeometry":"Tetrahedron",
            "TorusGeometry":"Torus",
            "TorusKnotGeometry":"TorusKnot",
            "Parametric":"Fancy",
            "AppleGeometry":"Apple",
            "AppleInvertedGeometry":"Inverted Apple",
            "FermatGeometry":"Fermat",
            "SpringGeometry":"Spring",
            "SpringInvertedGeometry":"Inverted Spring",
            "NaticaStellataGeometry":"Natica",
            "NaticaStellataInvertedGeometry":"Inverted Natica",
            "HelicoidGeometry":"Helicoid",
            "SpiralGeometry":"Spiral",
            "SpiralInvertedGeometry":"Inverted Spiral",
            "PillowGeometry":"Pillow",
            "PillowInvertedGeometry":"Inverted Pillow",
            "CatenoidGeometry":"Catenoid",
            "ScherkGeometry":"Scherk",
            "KleinGeometry":"Klein",
            "KleinInvertedGeometry":"Inverted Klein",
            "MobiusGeometry":"Mobius",
            "Mobius3DGeometry":"Mobius3D",
            "Mobius3DInvertedGeometry":"Inverted Mobius3D",
            "SnailGeometry":"Snail",
            "SnailInvertedGeometry":"Inverted Snail",
            "HornGeometry":"Horn",
            "HornInvertedGeometry":"Inverted Horn",
            "Custom":"3D Model",
            "map":"image",
            "AmbientLight":"Ambient Light",
            "DirectionalLight":"Directional Light",
            "HemisphereLight":"Hemisphere Light",
            "PointLight":"Point Light",
            "SpotLight":"Spot Light",
            "RectAreaLight":"Rectangle Area Light"
    }
    }
    show(item){
        return this.names[item]||item;
    }
}